version: '3'

vars:
  BUILD_DIR: out
  DEPLOY_BRANCH: gh-pages
  TIMESTAMP: '{{ now | date "2006-01-02 15:04:05" }}'

tasks:
  build:
    desc: Build and export static site to ./out
    cmds:
      - npm run build
    sources:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.jsx'
      - public/**/*
      - pages/**/*
      - app/**/*

  prepare-static:
    deps:
      - build
    desc: Copy gh-pages specific files into the exported site
    cmds:
      - test -f out/.nojekyll || touch out/.nojekyll
      - printf '%s\n' 'www.lblachnicki.com' > out/CNAME

  gh-pages-deploy:
    deps:
      - prepare-static
    cmds:
      - git worktree remove .deploy || true
      - git worktree add -B {{.DEPLOY_BRANCH}} .deploy origin/{{.DEPLOY_BRANCH}} || git worktree add -B {{.DEPLOY_BRANCH}} .deploy $(git rev-parse --verify {{.DEPLOY_BRANCH}} || echo "HEAD")
      - rm -rf .deploy/*
      - cp -r {{.BUILD_DIR}}/. .deploy/
      - cd .deploy && git add --all && git commit -m "Deploy {{.TIMESTAMP}}" || true
      - cd .deploy && git push origin {{.DEPLOY_BRANCH}}
      - cd ..
      - git worktree remove .deploy

  deploy:
    cmds:
      - git checkout master
      - task: gh-pages-deploy
      - git checkout master
