import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Łukasz Blachnicki | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h2>Projects</h2>
          todo
        </section>
      </main>
    </div>
  );
};

export default Home;
