import { ReactElement } from "react";
import 'node_modules/rehype-github-alerts/dist/styling/css/index.css'
import 'tocbot/dist/tocbot.css';
import Header from "../components/header";
import Footer from "../components/footer";
import Head from "next/head";

export type LayoutMeta = {
    title: string;
}

interface Props {
  children: ReactElement | ReactElement[];
  meta: LayoutMeta
}

export default function MainLayout({ children, meta }: Props) {
  return (
    <>
        <Head>
            <title>{`Łukasz Blachnicki | ${meta?.title}`}</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
      <Header />
      <main
        style={{
          minHeight: "calc(100vh - 60px - 60px)",
          display: "flex",
          flexDirection: "column",
          boxSizing: "border-box",
        }}
      >
        {children}
      </main>
      <Footer />
    </>
  );
}
