import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Łukasz Blachnicki | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <section>
              <div>
                  <Image
                      src="/gifs/john-travolta-lost.gif"
                      width="220"
                      height="212"
                      unoptimized
                  />
              </div>
          </section>
      </main>
    </div>
  );
};

export default Home;
