import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Łukasz Blachnicki | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <h2>GitHub activity</h2>
          <img
            src="http://ghchart.rshah.org/kartm"
            alt="Kartm's Github activity"
          ></img>
        </section>
      </main>
    </div>
  );
};

export default Home;
